-- Table: public.trips

-- DROP TABLE public.trips;

CREATE TABLE public.trips
(
    id bigint,
	listing_url text COLLATE pg_catalog."default",
    scrape_id bigint,
    last_scraped date,
    name character varying(255) COLLATE pg_catalog."default",
    summary text COLLATE pg_catalog."default",
    space text COLLATE pg_catalog."default",
    description text COLLATE pg_catalog."default",
    experiences_offered character varying(255) COLLATE pg_catalog."default",
    neighborhood_overview text COLLATE pg_catalog."default",
    notes text COLLATE pg_catalog."default",
    transit text COLLATE pg_catalog."default",
    access text COLLATE pg_catalog."default",
    interaction text COLLATE pg_catalog."default",
    house_rules text COLLATE pg_catalog."default",
    thumbnail_url text COLLATE pg_catalog."default",
	medium_url text COLLATE pg_catalog."default",
	picture_url text COLLATE pg_catalog."default",
	xl_picture_url text COLLATE pg_catalog."default",
	host_id	text COLLATE pg_catalog."default",
	host_url text COLLATE pg_catalog."default",
	host_name character varying(255) COLLATE pg_catalog."default",
	host_since date,
	host_location text COLLATE pg_catalog."default",
	host_about text COLLATE pg_catalog."default",
	host_response_time character varying(255) COLLATE pg_catalog."default",
	host_response_rate character varying(255) COLLATE pg_catalog."default",
	host_acceptance_rate character varying(255) COLLATE pg_catalog."default",
	host_is_superhost character varying(255) COLLATE pg_catalog."default",
	host_thumbnail_url text COLLATE pg_catalog."default",
	host_picture_url text COLLATE pg_catalog."default",
	host_neighbourhood character varying(255) COLLATE pg_catalog."default",
	host_listings_count	bigint,
	host_total_listings_count bigint,
	host_verifications text COLLATE pg_catalog."default",
	host_has_profile_pic character varying(255) COLLATE pg_catalog."default",
	host_identity_verified character varying(255) COLLATE pg_catalog."default",
	street character varying(255) COLLATE pg_catalog."default",
	neighbourhood character varying(255) COLLATE pg_catalog."default",
	neighbourhood_cleansed character varying(255) COLLATE pg_catalog."default",
	neighbourhood_group_cleansed character varying(255) COLLATE pg_catalog."default",
	city character varying(255) COLLATE pg_catalog."default",
	state character varying(255) COLLATE pg_catalog."default",
	zipcode	character varying(255) COLLATE pg_catalog."default",
	market character varying(255) COLLATE pg_catalog."default",
	smart_location character varying(255) COLLATE pg_catalog."default",
	country_code character varying(255) COLLATE pg_catalog."default",
	country	character varying(255) COLLATE pg_catalog."default",
	latitude double precision,
	longitude double precision,
	is_location_exact character varying(255) COLLATE pg_catalog."default",
	property_type character varying(255) COLLATE pg_catalog."default",
	room_type character varying(255) COLLATE pg_catalog."default",
	accommodates bigint,
	bathrooms double precision,
	bedrooms bigint,
	beds bigint,
	bed_type character varying(255) COLLATE pg_catalog."default",
	amenities text COLLATE pg_catalog."default",
	square_feet	bigint,
	price character varying(255) COLLATE pg_catalog."default",
	weekly_price character varying(255) COLLATE pg_catalog."default",
	monthly_price character varying(255) COLLATE pg_catalog."default",
	security_deposit character varying(255) COLLATE pg_catalog."default",
	cleaning_fee character varying(255) COLLATE pg_catalog."default",
	guests_included	bigint,
	extra_people character varying(255) COLLATE pg_catalog."default",
	minimum_nights bigint,
	maximum_nights bigint,
	calendar_updated character varying(255) COLLATE pg_catalog."default",
	has_availability character varying(255) COLLATE pg_catalog."default",
	availability_30	bigint,
	availability_60	bigint,
	availability_90	bigint,
	availability_365 bigint,
	calendar_last_scraped date,
	number_of_reviews bigint,
	first_review date,
	last_review	date,
	review_scores_rating bigint,
	review_scores_accuracy bigint,
	review_scores_cleanliness bigint,
	review_scores_checkin bigint,
	review_scores_communication bigint,
	review_scores_location bigint,
	review_scores_value bigint,
	requires_license character varying(255) COLLATE pg_catalog."default",
	license	character varying(255) COLLATE pg_catalog."default",
	jurisdiction_names character varying(255) COLLATE pg_catalog."default",
	instant_bookable character varying(255) COLLATE pg_catalog."default",
	is_business_travel_ready character varying(255) COLLATE pg_catalog."default",
	cancellation_policy character varying(255) COLLATE pg_catalog."default",
	require_guest_profile_picture character varying(255) COLLATE pg_catalog."default",
	require_guest_phone_verification character varying(255) COLLATE pg_catalog."default",
	calculated_host_listings_count bigint,
	reviews_per_month double precision
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE public.trips
    OWNER to postgres;